### ISSUE TITLE
[05주차]_9장_웹 크롤러 설계_윤철

### ISSUE THREAD

**Issue by icarus8050** [Meet-Coder-Study/book-system-design-interview#40]
* 153p
  * URL의 우선순위를 나눌 때 트래픽의 양을 알아낼 수 있는 방법이 뭐가 있을까요? 단순히 검색엔진을 통해서 자사 고객들이 검색에 노출되어 클릭되는 수를 가지고 추론하는 방법일까요?

**Comment by Wave1994-Hoon** [comment]
유튜브를 예를들자면 영상에 있는 조회수 혹은 좋아요 개수로 판단이 가능할 것 같습니다.
어느 사이트든 오픈 API 로 자사의 트래픽양을 공개라는 곳은 없기에 ... ㅠ.ㅠ
