### ISSUE TITLE
[01주차]_1장_사용자 수에 따른 규모 확장성_신선영

### ISSUE THREAD

**Issue by shinsunyoung** [Meet-Coder-Study/book-system-design-interview#5]
질문이라기보단 경험 공유를 듣고 싶은 부분입니다!!
다들 어떤 로그 시스템 / 텔레메트리 수집 시스템 / APM을 사용하고, 어떤식으로 활용하고 있는지 궁금해요~!

**Comment by Flamme1004K** [comment]
해당 질문 답변 도중 나온 SpringBoot에서 JPA SlowQuery 세팅 공유합니다.

- jpa: properties: hibernate: session: LOG_QUERIES_SLOWER_THAN_MS: 25

**Comment by shinsunyoung** [comment]
[로그 시스템]
- Elastic Search + Kibana
- Newrelic

[텔레메트리 수집 시스템]
- Prometheus + Grafana

[APM]
- Newrelic
- Pinpoint
- ELK
- Scouter
- Jennifer

**Comment by shinsunyoung** [comment]
[로그 시스템]
- Elastic Search + Kibana
- Newrelic

[텔레메트리 수집 시스템]
- Prometheus + Grafana

[APM]
- Newrelic
- Pinpoint
- ELK
- Scouter
- Jennifer
